"""the whole schema

Revision ID: 0001
Revises: 0000
Create Date: 2026-09-22 19:43:29.757522
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = "0000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_user_id_ulid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "capacity",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("hours_per_week", sa.Float(), nullable=False),
        sa.Column("from_date", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "hours_per_week > 0 AND hours_per_week <= 112", name=op.f("ck_capacity_hours_range")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_capacity_id_ulid")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_capacity_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity")),
    )
    with op.batch_alter_table("capacity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_capacity_user_id"), ["user_id"], unique=False)

    op.create_table(
        "course",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("instructor", sa.Text(), nullable=True),
        sa.Column("instructor_tier", sa.Text(), nullable=False),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("credits_tier", sa.Text(), nullable=False),
        sa.Column("target_grade", sa.Float(), nullable=True),
        sa.Column("strategy", sa.Text(), server_default=sa.text("'default'"), nullable=False),
        sa.Column("strategy_changed_at", sa.Text(), nullable=True),
        sa.Column("conceded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("conceded_at", sa.Text(), nullable=True),
        sa.Column("source_course_id", sa.Text(), nullable=True),
        sa.Column("semester_name", sa.Text(), nullable=False),
        sa.Column("semester_start", sa.Text(), nullable=True),
        sa.Column("semester_end", sa.Text(), nullable=True),
        sa.Column("semester_end_approx", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((credits_tier = 'unknown') AND (credits is NULL)) OR (NOT (credits_tier = 'unknown') AND NOT(credits is NULL))",
            name=op.f("ck_course_credits_tier_rule"),
        ),
        sa.CheckConstraint(
            "((instructor_tier = 'unknown') AND (instructor is NULL)) OR (NOT (instructor_tier = 'unknown') AND NOT(instructor is NULL))",
            name=op.f("ck_course_instructor_tier_rule"),
        ),
        sa.CheckConstraint(
            "credits_tier IN ('declared', 'inferred', 'unknown')",
            name=op.f("ck_course_credits_tier_enum"),
        ),
        sa.CheckConstraint(
            "instructor_tier IN ('declared', 'inferred', 'unknown')",
            name=op.f("ck_course_instructor_tier_enum"),
        ),
        sa.CheckConstraint(
            "strategy IN ('default', 'catch-up')", name=op.f("ck_course_strategy_enum")
        ),
        sa.CheckConstraint(
            "NOT (conceded = 1) OR (conceded_at IS NOT NULL)",
            name=op.f("ck_course_conceded_at_set"),
        ),
        sa.CheckConstraint("conceded IN (0,1)", name=op.f("ck_course_conceded_bool")),
        sa.CheckConstraint("credits > 0", name=op.f("ck_course_credits_range")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_course_id_ulid")),
        sa.CheckConstraint("semester_end > semester_start", name=op.f("ck_course_semester_order")),
        sa.CheckConstraint(
            "semester_end_approx IN (0,1)", name=op.f("ck_course_semester_end_approx_bool")
        ),
        sa.CheckConstraint("source_course_id IS NULL", name=op.f("ck_course_source_course_v1")),
        sa.CheckConstraint(
            "target_grade >= 0 AND target_grade <= 100", name=op.f("ck_course_target_grade_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_course_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course")),
    )
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_course_user_id"), ["user_id"], unique=False)

    op.create_table(
        "assessment_slot",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('exam', 'project', 'lab')", name=op.f("ck_assessment_slot_kind_enum")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_assessment_slot_id_ulid")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_assessment_slot_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_assessment_slot_owner_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_slot")),
    )
    with op.batch_alter_table("assessment_slot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assessment_slot_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "coverage_reading",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("denominator_tier", sa.Text(), nullable=False),
        sa.Column("tier_note", sa.Text(), nullable=False),
        sa.Column("computed_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "denominator_tier IN ('weighted', 'inferred', 'unweighted')",
            name=op.f("ck_coverage_reading_denominator_tier_enum"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_coverage_reading_id_ulid")),
        sa.CheckConstraint(
            "value >= 0 AND value <= 1", name=op.f("ck_coverage_reading_value_range")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_coverage_reading_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_coverage_reading_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_reading")),
    )
    with op.batch_alter_table("coverage_reading", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_coverage_reading_user_id"), ["user_id"], unique=False)

    op.create_table(
        "material",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_ref", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("has_text_layer", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("added_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('slides', 'chapter', 'lecture-notes', 'textbook', 'exercises', 'syllabus', 'other')",
            name=op.f("ck_material_kind_enum"),
        ),
        sa.CheckConstraint("has_text_layer IN (0,1)", name=op.f("ck_material_has_text_layer_bool")),
        sa.CheckConstraint("length(content_sha256) = 64", name=op.f("ck_material_sha256_len")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_material_id_ulid")),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk_material_course_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_material_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material")),
        sa.UniqueConstraint(
            "course_id", "content_sha256", name=op.f("uq_material_course_id_content_sha256")
        ),
    )
    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_material_user_id"), ["user_id"], unique=False)

    op.create_table(
        "plan",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("scope_course_id", sa.Text(), nullable=True),
        sa.Column("shown_n", sa.Integer(), nullable=False),
        sa.Column("strategy_snapshot", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((scope_course_id IS NOT NULL) AND (scope = 'course')) OR (NOT (scope_course_id IS NOT NULL) AND NOT(scope = 'course'))",
            name=op.f("ck_plan_course_scope_has_course"),
        ),
        sa.CheckConstraint("scope IN ('all-courses', 'course')", name=op.f("ck_plan_scope_enum")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_plan_id_ulid")),
        sa.CheckConstraint("shown_n >= 1", name=op.f("ck_plan_shown_n_min")),
        sa.ForeignKeyConstraint(
            ["scope_course_id"],
            ["course.id"],
            name=op.f("fk_plan_scope_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_plan_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
    )
    with op.batch_alter_table("plan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_user_id"), ["user_id"], unique=False)

    op.create_table(
        "study_session",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=True),
        sa.Column("subject_id", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("ended_at", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "NOT (position IS NOT NULL) OR (mode = 'exam-walkthrough')",
            name=op.f("ck_study_session_position_walkthrough_only"),
        ),
        sa.CheckConstraint(
            "mode IN ('explain-chapter', 'exam-walkthrough', 'mock', 'review-quiz')",
            name=op.f("ck_study_session_mode_enum"),
        ),
        sa.CheckConstraint(
            "source IN ('system', 'manual')", name=op.f("ck_study_session_source_enum")
        ),
        sa.CheckConstraint(
            "subject_type IN ('topic', 'material', 'past-exam')",
            name=op.f("ck_study_session_subject_type_enum"),
        ),
        sa.CheckConstraint(
            "((subject_id IS NULL) AND (subject_type IS NULL)) OR (NOT (subject_id IS NULL) AND NOT(subject_type IS NULL))",
            name=op.f("ck_study_session_subject_pair"),
        ),
        sa.CheckConstraint(
            "ended_at >= started_at", name=op.f("ck_study_session_ended_after_start")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_study_session_id_ulid")),
        sa.CheckConstraint("position >= 1", name=op.f("ck_study_session_position_min")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_study_session_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_study_session_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_session")),
    )
    with op.batch_alter_table("study_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "topic",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("superseded_by", sa.Text(), nullable=True),
        sa.Column("proposed_by", sa.Text(), nullable=False),
        sa.Column("status_changed_at", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "NOT (superseded_by IS NOT NULL) OR (status = 'superseded')",
            name=op.f("ck_topic_superseded_by_status"),
        ),
        sa.CheckConstraint(
            "proposed_by IN ('material', 'profile', 'split')",
            name=op.f("ck_topic_proposed_by_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'unexamined', 'superseded', 'declined')",
            name=op.f("ck_topic_status_enum"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_topic_id_ulid")),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk_topic_course_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["topic.id"],
            name=op.f("fk_topic_superseded_by"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_topic_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic")),
    )
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_user_id"), ["user_id"], unique=False)

    op.create_table(
        "assessment",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("slot_id", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("weight_tier", sa.Text(), nullable=False),
        sa.Column("date", sa.Text(), nullable=True),
        sa.Column("date_approx", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("time", sa.Text(), nullable=True),
        sa.Column("room", sa.Text(), nullable=True),
        sa.Column("session_type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'upcoming'"), nullable=False),
        sa.Column("mark", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((mark IS NOT NULL) AND (status = 'graded')) OR (NOT (mark IS NOT NULL) AND NOT(status = 'graded'))",
            name=op.f("ck_assessment_check_graded"),
        ),
        sa.CheckConstraint(
            "((weight_tier = 'unknown') AND (weight is NULL)) OR (NOT (weight_tier = 'unknown') AND NOT(weight is NULL))",
            name=op.f("ck_assessment_weight_tier_rule"),
        ),
        sa.CheckConstraint(
            "session_type IN ('first', 'second')", name=op.f("ck_assessment_session_type_enum")
        ),
        sa.CheckConstraint(
            "status IN ('upcoming', 'sat', 'graded')", name=op.f("ck_assessment_status_enum")
        ),
        sa.CheckConstraint(
            "weight_tier IN ('declared', 'inferred', 'unknown')",
            name=op.f("ck_assessment_weight_tier_enum"),
        ),
        sa.CheckConstraint(
            "NOT (date_approx = 1) OR (date IS NOT NULL)",
            name=op.f("ck_assessment_approx_needs_date"),
        ),
        sa.CheckConstraint("date_approx IN (0,1)", name=op.f("ck_assessment_date_approx_bool")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_assessment_id_ulid")),
        sa.CheckConstraint(
            "mark >= 0 AND mark <= 100", name=op.f("ck_assessment_mark_range_check")
        ),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 100", name=op.f("ck_assessment_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["assessment_slot.id"],
            name=op.f("fk_assessment_slot_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_assessment_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment")),
        sa.UniqueConstraint(
            "slot_id", "session_type", name=op.f("uq_assessment_slot_id_session_type")
        ),
    )
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.create_index("ix_assessment_user_date", ["user_id", "date"], unique=False)
        batch_op.create_index(batch_op.f("ix_assessment_user_id"), ["user_id"], unique=False)

    op.create_table(
        "exam_profile",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("slot_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("derived_at", sa.Text(), nullable=False),
        sa.Column(
            "provisional_syllabus", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "provisional_instructor", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("provisional_format", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "recency_weight_newest", sa.Integer(), server_default=sa.text("3"), nullable=False
        ),
        sa.Column(
            "recency_weight_next_two", sa.Integer(), server_default=sa.text("2"), nullable=False
        ),
        sa.Column(
            "recency_weight_older", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("evidence_count_syllabus", sa.Integer(), nullable=False),
        sa.Column("evidence_count_instructor", sa.Integer(), nullable=False),
        sa.Column("evidence_count_format", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "evidence_count_format >= 0", name=op.f("ck_exam_profile_count_format_min")
        ),
        sa.CheckConstraint(
            "evidence_count_instructor >= 0", name=op.f("ck_exam_profile_count_instructor_min")
        ),
        sa.CheckConstraint(
            "evidence_count_syllabus >= 0", name=op.f("ck_exam_profile_count_syllabus_min")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_exam_profile_id_ulid")),
        sa.CheckConstraint(
            "provisional_format IN (0,1)", name=op.f("ck_exam_profile_provisional_format_bool")
        ),
        sa.CheckConstraint(
            "provisional_instructor IN (0,1)",
            name=op.f("ck_exam_profile_provisional_instructor_bool"),
        ),
        sa.CheckConstraint(
            "provisional_syllabus IN (0,1)", name=op.f("ck_exam_profile_provisional_syllabus_bool")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_exam_profile_version_min")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_exam_profile_owner_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["assessment_slot.id"],
            name=op.f("fk_exam_profile_slot_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_profile")),
        sa.UniqueConstraint("slot_id", "version", name=op.f("uq_exam_profile_slot_id_version")),
    )
    with op.batch_alter_table("exam_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exam_profile_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "hours_entry",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("topic_id", sa.Text(), nullable=True),
        sa.Column("setup_key", sa.Text(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("deviation_reason", sa.Text(), nullable=True),
        sa.Column("voided_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "deviation_reason IN ('external-deadline', 'disagreed', 'too-tired', 'topic-wrong', 'unexplained')",
            name=op.f("ck_hours_entry_deviation_reason_enum"),
        ),
        sa.CheckConstraint(
            "source IN ('tool', 'timer', 'sweep')", name=op.f("ck_hours_entry_source_enum")
        ),
        sa.CheckConstraint(
            "NOT (topic_id IS NOT NULL AND setup_key IS NOT NULL)",
            name=op.f("ck_hours_entry_one_scope"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_hours_entry_id_ulid")),
        sa.CheckConstraint(
            "minutes >= 1 AND minutes <= 720", name=op.f("ck_hours_entry_minutes_range")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk_hours_entry_course_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["study_session.id"],
            name=op.f("fk_hours_entry_session_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_hours_entry_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_hours_entry_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hours_entry")),
    )
    with op.batch_alter_table("hours_entry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hours_entry_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_hours_entry_user_occurred", ["user_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_hours_entry_user_setup", ["user_id", "setup_key"], unique=False)

    op.create_table(
        "topic_split",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("parent_topic_id", sa.Text(), nullable=False),
        sa.Column("child_topic_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "child_topic_id <> parent_topic_id", name=op.f("ck_topic_split_not_self")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_topic_split_id_ulid")),
        sa.ForeignKeyConstraint(
            ["child_topic_id"],
            ["topic.id"],
            name=op.f("fk_topic_split_child_topic_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_topic_id"],
            ["topic.id"],
            name=op.f("fk_topic_split_parent_topic_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_topic_split_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_split")),
        sa.UniqueConstraint(
            "parent_topic_id",
            "child_topic_id",
            name=op.f("uq_topic_split_parent_topic_id_child_topic_id"),
        ),
    )
    with op.batch_alter_table("topic_split", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_split_user_id"), ["user_id"], unique=False)

    op.create_table(
        "topic_state",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due_at", sa.Text(), nullable=True),
        sa.Column("last_reviewed_at", sa.Text(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("inferred", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint("inferred IN (0,1)", name=op.f("ck_topic_state_inferred_bool")),
        sa.CheckConstraint("lapses >= 0", name=op.f("ck_topic_state_lapses_min")),
        sa.CheckConstraint("reps >= 0", name=op.f("ck_topic_state_reps_min")),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_topic_state_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_topic_state_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id", "topic_id", name=op.f("pk_topic_state")),
    )
    with op.batch_alter_table("topic_state", schema=None) as batch_op:
        batch_op.create_index("ix_topic_state_user_due", ["user_id", "due_at"], unique=False)

    op.create_table(
        "coverage",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("assessment_id", sa.Text(), nullable=True),
        sa.Column("material_id", sa.Text(), nullable=True),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("confirmed_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("tier IN ('declared', 'inferred')", name=op.f("ck_coverage_tier_enum")),
        sa.CheckConstraint(
            "CASE WHEN material_id IS NULL THEN 0 ELSE 1 END + CASE WHEN assessment_id IS NULL THEN 0 ELSE 1 END = 1",
            name=op.f("ck_coverage_exactly_one"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_coverage_id_ulid")),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
            name=op.f("fk_coverage_assessment_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
            name=op.f("fk_coverage_material_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_coverage_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_coverage_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage")),
    )
    with op.batch_alter_table("coverage", schema=None) as batch_op:
        batch_op.create_index("ix_coverage_material", ["material_id"], unique=False)
        batch_op.create_index("ix_coverage_topic", ["topic_id"], unique=False)
        batch_op.create_index(
            "ix_coverage_user_confirmed", ["user_id", "confirmed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_coverage_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ux_coverage_assessment",
            ["topic_id", "assessment_id"],
            unique=True,
            sqlite_where=sa.text("assessment_id IS NOT NULL"),
            postgresql_where=sa.text("assessment_id IS NOT NULL"),
        )
        batch_op.create_index(
            "ux_coverage_material",
            ["topic_id", "material_id"],
            unique=True,
            sqlite_where=sa.text("material_id IS NOT NULL"),
            postgresql_where=sa.text("material_id IS NOT NULL"),
        )

    op.create_table(
        "generation_task",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("scope_type", sa.Text(), nullable=False),
        sa.Column("scope_id", sa.Text(), nullable=False),
        sa.Column("exam_profile_id", sa.Text(), nullable=True),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("bytes_sent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("bytes_returned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("superseded_by", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("closed_at", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "((closed_at IS NOT NULL) AND (status <> 'open')) OR (NOT (closed_at IS NOT NULL) AND NOT(status <> 'open'))",
            name=op.f("ck_generation_task_closed_when_not_open"),
        ),
        sa.CheckConstraint(
            "((superseded_by IS NOT NULL) AND (status = 'superseded')) OR (NOT (superseded_by IS NOT NULL) AND NOT(status = 'superseded'))",
            name=op.f("ck_generation_task_superseded_by_status"),
        ),
        sa.CheckConstraint(
            "kind IN ('note', 'practice', 'memory', 'transcription', 'timetable')",
            name=op.f("ck_generation_task_kind_enum"),
        ),
        sa.CheckConstraint(
            "route IN ('host', 'sampling')", name=op.f("ck_generation_task_route_enum")
        ),
        sa.CheckConstraint(
            "scope_type IN ('course', 'material', 'topic', 'past-exam', 'user')",
            name=op.f("ck_generation_task_scope_type_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed', 'partial', 'superseded', 'invalidated')",
            name=op.f("ck_generation_task_status_enum"),
        ),
        sa.CheckConstraint(
            "bytes_returned >= 0", name=op.f("ck_generation_task_bytes_returned_min")
        ),
        sa.CheckConstraint("bytes_sent >= 0", name=op.f("ck_generation_task_bytes_sent_min")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_generation_task_id_ulid")),
        sa.ForeignKeyConstraint(
            ["exam_profile_id"],
            ["exam_profile.id"],
            name=op.f("fk_generation_task_exam_profile_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["generation_task.id"],
            name=op.f("fk_generation_task_superseded_by"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_generation_task_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_task")),
    )
    with op.batch_alter_table("generation_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_generation_task_user_id"), ["user_id"], unique=False)

    op.create_table(
        "plan_item",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("plan_id", sa.Text(), nullable=False),
        sa.Column("lane", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=True),
        sa.Column("setup_kind", sa.Text(), nullable=True),
        sa.Column("setup_key", sa.Text(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("shown", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("marks_unlocked_estimate", sa.Float(), nullable=True),
        sa.Column("exam_profile_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "((score IS NOT NULL) AND (lane <> 'setup')) OR (NOT (score IS NOT NULL) AND NOT(lane <> 'setup'))",
            name=op.f("ck_plan_item_score_unless_setup"),
        ),
        sa.CheckConstraint(
            "((setup_key IS NOT NULL) AND (lane = 'setup')) OR (NOT (setup_key IS NOT NULL) AND NOT(lane = 'setup'))",
            name=op.f("ck_plan_item_setup_key_for_setup"),
        ),
        sa.CheckConstraint(
            "((setup_kind IS NOT NULL) AND (lane = 'setup')) OR (NOT (setup_kind IS NOT NULL) AND NOT(lane = 'setup'))",
            name=op.f("ck_plan_item_setup_kind_for_setup"),
        ),
        sa.CheckConstraint(
            "((topic_id IS NOT NULL) AND (lane <> 'setup')) OR (NOT (topic_id IS NOT NULL) AND NOT(lane <> 'setup'))",
            name=op.f("ck_plan_item_topic_unless_setup"),
        ),
        sa.CheckConstraint(
            "NOT (lane = 'setup') OR (estimated_minutes IS NULL)",
            name=op.f("ck_plan_item_setup_has_no_minutes"),
        ),
        sa.CheckConstraint(
            "NOT (marks_unlocked_estimate IS NOT NULL) OR (lane = 'setup')",
            name=op.f("ck_plan_item_marks_unlocked_setup_only"),
        ),
        sa.CheckConstraint(
            "lane IN ('review', 'study', 'setup')", name=op.f("ck_plan_item_lane_enum")
        ),
        sa.CheckConstraint(
            "setup_kind IN ('grading', 'credits', 'exam-date', 'target-grade', 'first-material', 'past-papers')",
            name=op.f("ck_plan_item_setup_kind_enum"),
        ),
        sa.CheckConstraint(
            "estimated_minutes > 0", name=op.f("ck_plan_item_estimated_minutes_min")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_plan_item_id_ulid")),
        sa.CheckConstraint(
            "marks_unlocked_estimate >= 0", name=op.f("ck_plan_item_marks_unlocked_min")
        ),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_plan_item_rank_min")),
        sa.CheckConstraint("shown IN (0,1)", name=op.f("ck_plan_item_shown_bool")),
        sa.ForeignKeyConstraint(
            ["course_id"], ["course.id"], name=op.f("fk_plan_item_course_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["exam_profile_id"],
            ["exam_profile.id"],
            name=op.f("fk_plan_item_exam_profile_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plan.id"], name=op.f("fk_plan_item_plan_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_plan_item_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_plan_item_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_item")),
        sa.UniqueConstraint("plan_id", "lane", "rank", name=op.f("uq_plan_item_plan_id_lane_rank")),
    )
    with op.batch_alter_table("plan_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_item_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_plan_item_user_setup", ["user_id", "setup_key"], unique=False)
        batch_op.create_index("ix_plan_item_user_topic", ["user_id", "topic_id"], unique=False)

    op.create_table(
        "topic_weight",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("exam_profile_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_topic_weight_id_ulid")),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 100", name=op.f("ck_topic_weight_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["exam_profile_id"],
            ["exam_profile.id"],
            name=op.f("fk_topic_weight_exam_profile_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_topic_weight_topic_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_weight")),
        sa.UniqueConstraint(
            "exam_profile_id", "topic_id", name=op.f("uq_topic_weight_exam_profile_id_topic_id")
        ),
    )
    op.create_table(
        "capacity_suggestion",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("hours_per_week", sa.Float(), nullable=False),
        sa.Column("source_task_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((resolved_at IS NOT NULL) AND (status <> 'pending')) OR (NOT (resolved_at IS NOT NULL) AND NOT(status <> 'pending'))",
            name=op.f("ck_capacity_suggestion_resolved_when_done"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'dismissed')",
            name=op.f("ck_capacity_suggestion_status_enum"),
        ),
        sa.CheckConstraint(
            "hours_per_week > 0", name=op.f("ck_capacity_suggestion_hours_positive")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_capacity_suggestion_id_ulid")),
        sa.ForeignKeyConstraint(
            ["source_task_id"],
            ["generation_task.id"],
            name=op.f("fk_capacity_suggestion_source_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_capacity_suggestion_user_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_suggestion")),
    )
    with op.batch_alter_table("capacity_suggestion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capacity_suggestion_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "class_meeting",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Text(), nullable=False),
        sa.Column("end_time", sa.Text(), nullable=False),
        sa.Column("room", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("source_task_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('lecture', 'lab', 'tutorial')", name=op.f("ck_class_meeting_kind_enum")
        ),
        sa.CheckConstraint(
            "tier IN ('declared', 'inferred')", name=op.f("ck_class_meeting_tier_enum")
        ),
        sa.CheckConstraint("end_time > start_time", name=op.f("ck_class_meeting_time_order")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_class_meeting_id_ulid")),
        sa.CheckConstraint(
            "weekday >= 1 AND weekday <= 7", name=op.f("ck_class_meeting_weekday_iso")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_class_meeting_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_task_id"],
            ["generation_task.id"],
            name=op.f("fk_class_meeting_source_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_class_meeting_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_meeting")),
        sa.UniqueConstraint(
            "course_id",
            "weekday",
            "start_time",
            "kind",
            name=op.f("uq_class_meeting_course_id_weekday_start_time_kind"),
        ),
    )
    with op.batch_alter_table("class_meeting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_class_meeting_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memory_item",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("item_ordinal", sa.Integer(), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'live'"), nullable=False),
        sa.Column("source_marker", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "source_marker IN ('from-material', 'model-knowledge')",
            name=op.f("ck_memory_item_source_marker_enum"),
        ),
        sa.CheckConstraint(
            "state IN ('live', 'needs-review', 'rejected', 'superseded')",
            name=op.f("ck_memory_item_state_enum"),
        ),
        sa.CheckConstraint("item_ordinal >= 1", name=op.f("ck_memory_item_item_ordinal_min")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_memory_item_id_ulid")),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["generation_task.id"],
            name=op.f("fk_memory_item_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_memory_item_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_memory_item_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_item")),
        sa.UniqueConstraint(
            "task_id", "item_ordinal", name=op.f("uq_memory_item_task_id_item_ordinal")
        ),
    )
    with op.batch_alter_table("memory_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_item_user_id"), ["user_id"], unique=False)

    op.create_table(
        "note",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("material_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("section_ordinal", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("exam_profile_id", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("exported_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_note_id_ulid")),
        sa.CheckConstraint("section_ordinal >= 1", name=op.f("ck_note_section_ordinal_min")),
        sa.ForeignKeyConstraint(
            ["exam_profile_id"],
            ["exam_profile.id"],
            name=op.f("fk_note_exam_profile_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["material.id"], name=op.f("fk_note_material_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["generation_task.id"], name=op.f("fk_note_task_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_note_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note")),
        sa.UniqueConstraint(
            "task_id", "section_ordinal", name=op.f("uq_note_task_id_section_ordinal")
        ),
    )
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_note_user_id"), ["user_id"], unique=False)

    op.create_table(
        "past_exam",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("slot_id", sa.Text(), nullable=False),
        sa.Column("session_type", sa.Text(), nullable=False),
        sa.Column("session_date", sa.Text(), nullable=False),
        sa.Column("session_delayed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("instructor", sa.Text(), nullable=True),
        sa.Column("instructor_tier", sa.Text(), nullable=False),
        sa.Column("has_text_layer", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("file_ref", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("transcript_task_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((instructor_tier = 'unknown') AND (instructor is NULL)) OR (NOT (instructor_tier = 'unknown') AND NOT(instructor is NULL))",
            name=op.f("ck_past_exam_instructor_tier_rule"),
        ),
        sa.CheckConstraint(
            "instructor_tier IN ('declared', 'inferred', 'unknown')",
            name=op.f("ck_past_exam_instructor_tier_enum"),
        ),
        sa.CheckConstraint(
            "session_type IN ('first', 'second')", name=op.f("ck_past_exam_session_type_enum")
        ),
        sa.CheckConstraint(
            "has_text_layer IN (0,1)", name=op.f("ck_past_exam_has_text_layer_bool")
        ),
        sa.CheckConstraint("length(content_sha256) = 64", name=op.f("ck_past_exam_sha256_len")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_past_exam_id_ulid")),
        sa.CheckConstraint(
            "session_delayed IN (0,1)", name=op.f("ck_past_exam_session_delayed_bool")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_past_exam_owner_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["assessment_slot.id"],
            name=op.f("fk_past_exam_slot_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_task_id"],
            ["generation_task.id"],
            name=op.f("fk_past_exam_transcript_task_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_past_exam")),
        sa.UniqueConstraint(
            "slot_id", "content_sha256", name=op.f("uq_past_exam_slot_id_content_sha256")
        ),
    )
    with op.batch_alter_table("past_exam", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_past_exam_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_past_exam_slot_date", ["slot_id", "session_date"], unique=False)

    op.create_table(
        "submission",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("validation_result", sa.Text(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("bytes_sent", sa.Integer(), nullable=False),
        sa.Column("bytes_returned", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("accepted_count >= 0", name=op.f("ck_submission_accepted_min")),
        sa.CheckConstraint("bytes_returned >= 0", name=op.f("ck_submission_bytes_returned_min")),
        sa.CheckConstraint("bytes_sent >= 0", name=op.f("ck_submission_bytes_sent_min")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_submission_id_ulid")),
        sa.CheckConstraint(
            "ordinal >= 1 AND ordinal <= 3", name=op.f("ck_submission_ordinal_range")
        ),
        sa.CheckConstraint("rejected_count >= 0", name=op.f("ck_submission_rejected_min")),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["generation_task.id"],
            name=op.f("fk_submission_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_submission_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission")),
        sa.UniqueConstraint("task_id", "ordinal", name=op.f("uq_submission_task_id_ordinal")),
    )
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_submission_user_id"), ["user_id"], unique=False)

    op.create_table(
        "observation",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("slot_id", sa.Text(), nullable=False),
        sa.Column("past_exam_id", sa.Text(), nullable=True),
        sa.Column("claim_key", sa.Text(), nullable=False),
        sa.Column("claim_class", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=True),
        sa.Column("claim_value", sa.Text(), nullable=False),
        sa.Column("study_tier", sa.Text(), nullable=False),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((topic_id IS NOT NULL) AND (claim_key = 'topic-marks')) OR (NOT (topic_id IS NOT NULL) AND NOT(claim_key = 'topic-marks'))",
            name=op.f("ck_observation_topic_for_marks"),
        ),
        sa.CheckConstraint(
            "(claim_key IN ('topic-marks') AND claim_class = 'syllabus-driven') OR (claim_key IN ('duration-minutes', 'total-marks', 'question-count', 'has-mcq') AND claim_class = 'format') OR (claim_key IN ('archetype', 'phrasing', 'trap') AND claim_class = 'instructor-driven')",
            name=op.f("ck_observation_claim_class_by_key"),
        ),
        sa.CheckConstraint(
            "claim_class IN ('syllabus-driven', 'format', 'instructor-driven')",
            name=op.f("ck_observation_claim_class_enum"),
        ),
        sa.CheckConstraint(
            "claim_key IN ('topic-marks', 'duration-minutes', 'total-marks', 'question-count', 'has-mcq', 'archetype', 'phrasing', 'trap')",
            name=op.f("ck_observation_claim_key_enum"),
        ),
        sa.CheckConstraint(
            "study_tier IN ('E1', 'E2', 'E3')", name=op.f("ck_observation_study_tier_enum")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_observation_id_ulid")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_observation_owner_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["past_exam_id"],
            ["past_exam.id"],
            name=op.f("fk_observation_past_exam_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["assessment_slot.id"],
            name=op.f("fk_observation_slot_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_observation_topic_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation")),
    )
    with op.batch_alter_table("observation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_observation_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "practice_item",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("item_ordinal", sa.Integer(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("past_exam_id", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer_key", sa.Text(), nullable=True),
        sa.Column("answer_provenance", sa.Text(), nullable=False),
        sa.Column("marks", sa.Float(), nullable=True),
        sa.Column("state", sa.Text(), server_default=sa.text("'live'"), nullable=False),
        sa.Column("source_marker", sa.Text(), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("nearest_item_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "((answer_provenance = 'none') AND (answer_key IS NULL)) OR (NOT (answer_provenance = 'none') AND NOT(answer_key IS NULL))",
            name=op.f("ck_practice_item_answer_exists"),
        ),
        sa.CheckConstraint(
            "((novelty_score IS NOT NULL) AND (origin = 'generated')) OR (NOT (novelty_score IS NOT NULL) AND NOT(origin = 'generated'))",
            name=op.f("ck_practice_item_novelty_generated"),
        ),
        sa.CheckConstraint(
            "((past_exam_id IS NOT NULL) AND (origin = 'past-exam')) OR (NOT (past_exam_id IS NOT NULL) AND NOT(origin = 'past-exam'))",
            name=op.f("ck_practice_item_past_exam_origin"),
        ),
        sa.CheckConstraint(
            "NOT (origin = 'past-exam') OR (source_marker = 'from-material')",
            name=op.f("ck_practice_item_past_exam_marker"),
        ),
        sa.CheckConstraint(
            "answer_provenance IN ('verified-source', 'unverified', 'none')",
            name=op.f("ck_practice_item_answer_provenance_enum"),
        ),
        sa.CheckConstraint(
            "origin IN ('generated', 'past-exam', 'textbook', 'instructor-set')",
            name=op.f("ck_practice_item_origin_enum"),
        ),
        sa.CheckConstraint(
            "source_marker IN ('from-material', 'model-knowledge')",
            name=op.f("ck_practice_item_source_marker_enum"),
        ),
        sa.CheckConstraint(
            "state IN ('live', 'needs-review', 'rejected', 'superseded')",
            name=op.f("ck_practice_item_state_enum"),
        ),
        sa.CheckConstraint(
            "((position IS NOT NULL) AND (past_exam_id IS NOT NULL)) OR (NOT (position IS NOT NULL) AND NOT(past_exam_id IS NOT NULL))",
            name=op.f("ck_practice_item_position_past_exam"),
        ),
        sa.CheckConstraint("item_ordinal >= 1", name=op.f("ck_practice_item_item_ordinal_min")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_practice_item_id_ulid")),
        sa.CheckConstraint("marks >= 0", name=op.f("ck_practice_item_marks_min")),
        sa.CheckConstraint(
            "novelty_score >= 0 AND novelty_score <= 1", name=op.f("ck_practice_item_novelty_range")
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_practice_item_position_min")),
        sa.ForeignKeyConstraint(
            ["nearest_item_id"],
            ["practice_item.id"],
            name=op.f("fk_practice_item_nearest_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["past_exam_id"],
            ["past_exam.id"],
            name=op.f("fk_practice_item_past_exam_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["generation_task.id"],
            name=op.f("fk_practice_item_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_practice_item_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_practice_item_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_item")),
        sa.UniqueConstraint(
            "task_id", "item_ordinal", name=op.f("uq_practice_item_task_id_item_ordinal")
        ),
    )
    with op.batch_alter_table("practice_item", schema=None) as batch_op:
        batch_op.create_index("ix_practice_item_origin_topic", ["origin", "topic_id"], unique=False)
        batch_op.create_index("ix_practice_item_topic_state", ["topic_id", "state"], unique=False)
        batch_op.create_index(batch_op.f("ix_practice_item_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ux_practice_item_position",
            ["past_exam_id", "position"],
            unique=True,
            sqlite_where=sa.text("past_exam_id IS NOT NULL"),
            postgresql_where=sa.text("past_exam_id IS NOT NULL"),
        )

    op.create_table(
        "attempt",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("practice_item_id", sa.Text(), nullable=True),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("assisted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("fix_rule", sa.Text(), nullable=True),
        sa.Column("correctness_voided", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "NOT (session_id IS NULL) OR (source IN ('self-reported', 'exam-retro'))",
            name=op.f("ck_attempt_no_session_only_offline"),
        ),
        sa.CheckConstraint(
            "NOT (source = 'exam-walkthrough') OR (assisted = 1)",
            name=op.f("ck_attempt_walkthrough_is_assisted"),
        ),
        sa.CheckConstraint(
            "root_cause IN ('concept', 'recall', 'procedure', 'misread', 'careless', 'time-pressure')",
            name=op.f("ck_attempt_root_cause_enum"),
        ),
        sa.CheckConstraint(
            "source IN ('comprehension-check', 'practice', 'review-quiz', 'exam-walkthrough', 'exam-retro', 'self-reported')",
            name=op.f("ck_attempt_source_enum"),
        ),
        sa.CheckConstraint("assisted IN (0,1)", name=op.f("ck_attempt_assisted_bool")),
        sa.CheckConstraint("correct IN (0,1)", name=op.f("ck_attempt_correct_bool")),
        sa.CheckConstraint(
            "correct IS NOT NULL OR score IS NOT NULL", name=op.f("ck_attempt_some_result")
        ),
        sa.CheckConstraint(
            "correctness_voided IN (0,1)", name=op.f("ck_attempt_correctness_voided_bool")
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_attempt_id_ulid")),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_attempt_score_range")),
        sa.ForeignKeyConstraint(
            ["practice_item_id"],
            ["practice_item.id"],
            name=op.f("fk_attempt_practice_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["study_session.id"],
            name=op.f("fk_attempt_session_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name=op.f("fk_attempt_topic_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_attempt_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt")),
    )
    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attempt_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_attempt_user_topic", ["user_id", "topic_id"], unique=False)

    op.create_table(
        "discrimination_trial",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("practice_item_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("was_generated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("flagged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tell", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "tell IN ('too-easy', 'phrasing', 'topic-scope', 'formatting', 'no-tell')",
            name=op.f("ck_discrimination_trial_tell_enum"),
        ),
        sa.CheckConstraint("flagged IN (0,1)", name=op.f("ck_discrimination_trial_flagged_bool")),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_discrimination_trial_id_ulid")),
        sa.CheckConstraint(
            "was_generated IN (0,1)", name=op.f("ck_discrimination_trial_was_generated_bool")
        ),
        sa.ForeignKeyConstraint(
            ["practice_item_id"],
            ["practice_item.id"],
            name=op.f("fk_discrimination_trial_practice_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["study_session.id"],
            name=op.f("fk_discrimination_trial_session_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
            name=op.f("fk_discrimination_trial_topic_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_discrimination_trial_user_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discrimination_trial")),
        sa.UniqueConstraint(
            "session_id",
            "practice_item_id",
            name=op.f("uq_discrimination_trial_session_id_practice_item_id"),
        ),
    )
    with op.batch_alter_table("discrimination_trial", schema=None) as batch_op:
        batch_op.create_index(
            "ix_discrimination_trial_user_generated", ["user_id", "was_generated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_discrimination_trial_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "evidence",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("practice_item_id", sa.Text(), nullable=True),
        sa.Column("memory_item_id", sa.Text(), nullable=True),
        sa.Column("observation_id", sa.Text(), nullable=True),
        sa.Column("study_tier", sa.Text(), nullable=False),
        sa.Column("locator", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "study_tier IN ('E1', 'E2', 'E3')", name=op.f("ck_evidence_study_tier_enum")
        ),
        sa.CheckConstraint(
            "CASE WHEN practice_item_id IS NULL THEN 0 ELSE 1 END + CASE WHEN memory_item_id IS NULL THEN 0 ELSE 1 END + CASE WHEN observation_id IS NULL THEN 0 ELSE 1 END = 1",
            name=op.f("ck_evidence_exactly_one"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_evidence_id_ulid")),
        sa.ForeignKeyConstraint(
            ["memory_item_id"],
            ["memory_item.id"],
            name=op.f("fk_evidence_memory_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
            name=op.f("fk_evidence_observation_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practice_item_id"],
            ["practice_item.id"],
            name=op.f("fk_evidence_practice_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_evidence_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_user_id"), ["user_id"], unique=False)

    op.create_table(
        "item_rejection",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("practice_item_id", sa.Text(), nullable=True),
        sa.Column("memory_item_id", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "NOT (reason = 'wrong-answer-key') OR (practice_item_id IS NOT NULL)",
            name=op.f("ck_item_rejection_answer_key_is_practice"),
        ),
        sa.CheckConstraint(
            "reason IN ('off-syllabus', 'wrong-answer-key', 'wrong-topic', 'duplicate', 'unclear', 'wrong-difficulty')",
            name=op.f("ck_item_rejection_reason_enum"),
        ),
        sa.CheckConstraint(
            "CASE WHEN practice_item_id IS NULL THEN 0 ELSE 1 END + CASE WHEN memory_item_id IS NULL THEN 0 ELSE 1 END = 1",
            name=op.f("ck_item_rejection_exactly_one"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_item_rejection_id_ulid")),
        sa.ForeignKeyConstraint(
            ["memory_item_id"],
            ["memory_item.id"],
            name=op.f("fk_item_rejection_memory_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["practice_item_id"],
            ["practice_item.id"],
            name=op.f("fk_item_rejection_practice_item_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_item_rejection_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_rejection")),
    )
    with op.batch_alter_table("item_rejection", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_rejection_user_id"), ["user_id"], unique=False)

    op.create_table(
        "generation_directive",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Text(), nullable=True),
        sa.Column("topic_id", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'proposed'"), nullable=False),
        sa.Column("superseded_by", sa.Text(), nullable=True),
        sa.Column("source_rejection_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("confirmed_at", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "((confirmed_at IS NOT NULL) AND (status <> 'proposed')) OR (NOT (confirmed_at IS NOT NULL) AND NOT(status <> 'proposed'))",
            name=op.f("ck_generation_directive_confirmed_when_not_proposed"),
        ),
        sa.CheckConstraint(
            "((superseded_by IS NOT NULL) AND (status = 'superseded')) OR (NOT (superseded_by IS NOT NULL) AND NOT(status = 'superseded'))",
            name=op.f("ck_generation_directive_superseded_by_status"),
        ),
        sa.CheckConstraint(
            "kind IN ('format-preference', 'generator-correction')",
            name=op.f("ck_generation_directive_kind_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'superseded')",
            name=op.f("ck_generation_directive_status_enum"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_generation_directive_id_ulid")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_generation_directive_course_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_rejection_id"],
            ["item_rejection.id"],
            name=op.f("fk_generation_directive_source_rejection_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["generation_directive.id"],
            name=op.f("fk_generation_directive_superseded_by"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
            name=op.f("fk_generation_directive_topic_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_generation_directive_user_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_directive")),
    )
    with op.batch_alter_table("generation_directive", schema=None) as batch_op:
        batch_op.create_index(
            "ix_generation_directive_course_status", ["course_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_generation_directive_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_generation_directive_user_status", ["user_id", "status"], unique=False
        )

    op.create_table(
        "replacement_queue",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.Text(), nullable=False),
        sa.Column("rejection_id", sa.Text(), nullable=True),
        sa.Column("closed_task_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("filled_by_task_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "((filled_by_task_id IS NOT NULL) AND (status = 'filled')) OR (NOT (filled_by_task_id IS NOT NULL) AND NOT(status = 'filled'))",
            name=op.f("ck_replacement_queue_filled_by_when_filled"),
        ),
        sa.CheckConstraint(
            "((resolved_at IS NOT NULL) AND (status <> 'pending')) OR (NOT (resolved_at IS NOT NULL) AND NOT(status <> 'pending'))",
            name=op.f("ck_replacement_queue_resolved_when_done"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'filled', 'dropped')",
            name=op.f("ck_replacement_queue_status_enum"),
        ),
        sa.CheckConstraint(
            "CASE WHEN rejection_id IS NULL THEN 0 ELSE 1 END + CASE WHEN closed_task_id IS NULL THEN 0 ELSE 1 END = 1",
            name=op.f("ck_replacement_queue_exactly_one"),
        ),
        sa.CheckConstraint("length(id) = 26", name=op.f("ck_replacement_queue_id_ulid")),
        sa.ForeignKeyConstraint(
            ["closed_task_id"],
            ["generation_task.id"],
            name=op.f("fk_replacement_queue_closed_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["filled_by_task_id"],
            ["generation_task.id"],
            name=op.f("fk_replacement_queue_filled_by_task_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rejection_id"],
            ["item_rejection.id"],
            name=op.f("fk_replacement_queue_rejection_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
            name=op.f("fk_replacement_queue_topic_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_replacement_queue_user_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replacement_queue")),
    )
    with op.batch_alter_table("replacement_queue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_replacement_queue_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_replacement_queue_user_status", ["user_id", "status"], unique=False
        )

    # ### end Alembic commands ###

    # Case-insensitive uniqueness, one index per case-insensitive name (Conventions). Written by
    # hand: autogenerate skips an expression-based index because SQLite cannot reflect one, so
    # these three would go missing from every regeneration, not just this one.
    op.create_index(
        "ux_course_code",
        "course",
        [sa.text("user_id"), sa.text("lower(code)"), sa.text("semester_name")],
        unique=True,
    )
    op.create_index(
        "ux_assessment_slot_name",
        "assessment_slot",
        [sa.text("course_id"), sa.text("lower(name)")],
        unique=True,
    )
    op.create_index(
        "ux_topic_live",
        "topic",
        [sa.text("course_id"), sa.text("lower(name)")],
        unique=True,
        sqlite_where=sa.text("status IN ('proposed', 'active', 'unexamined')"),
        postgresql_where=sa.text("status IN ('proposed', 'active', 'unexamined')"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_topic_live", table_name="topic")
    op.drop_index("ux_assessment_slot_name", table_name="assessment_slot")
    op.drop_index("ux_course_code", table_name="course")
    with op.batch_alter_table("replacement_queue", schema=None) as batch_op:
        batch_op.drop_index("ix_replacement_queue_user_status")
        batch_op.drop_index(batch_op.f("ix_replacement_queue_user_id"))

    op.drop_table("replacement_queue")
    with op.batch_alter_table("generation_directive", schema=None) as batch_op:
        batch_op.drop_index("ix_generation_directive_user_status")
        batch_op.drop_index(batch_op.f("ix_generation_directive_user_id"))
        batch_op.drop_index("ix_generation_directive_course_status")

    op.drop_table("generation_directive")
    with op.batch_alter_table("item_rejection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_rejection_user_id"))

    op.drop_table("item_rejection")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_user_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("discrimination_trial", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discrimination_trial_user_id"))
        batch_op.drop_index("ix_discrimination_trial_user_generated")

    op.drop_table("discrimination_trial")
    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.drop_index("ix_attempt_user_topic")
        batch_op.drop_index(batch_op.f("ix_attempt_user_id"))

    op.drop_table("attempt")
    with op.batch_alter_table("practice_item", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_practice_item_position",
            sqlite_where=sa.text("past_exam_id IS NOT NULL"),
            postgresql_where=sa.text("past_exam_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_practice_item_user_id"))
        batch_op.drop_index("ix_practice_item_topic_state")
        batch_op.drop_index("ix_practice_item_origin_topic")

    op.drop_table("practice_item")
    with op.batch_alter_table("observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observation_owner_id"))

    op.drop_table("observation")
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_user_id"))

    op.drop_table("submission")
    with op.batch_alter_table("past_exam", schema=None) as batch_op:
        batch_op.drop_index("ix_past_exam_slot_date")
        batch_op.drop_index(batch_op.f("ix_past_exam_owner_id"))

    op.drop_table("past_exam")
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_note_user_id"))

    op.drop_table("note")
    with op.batch_alter_table("memory_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_item_user_id"))

    op.drop_table("memory_item")
    with op.batch_alter_table("class_meeting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_class_meeting_user_id"))

    op.drop_table("class_meeting")
    with op.batch_alter_table("capacity_suggestion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capacity_suggestion_user_id"))

    op.drop_table("capacity_suggestion")
    op.drop_table("topic_weight")
    with op.batch_alter_table("plan_item", schema=None) as batch_op:
        batch_op.drop_index("ix_plan_item_user_topic")
        batch_op.drop_index("ix_plan_item_user_setup")
        batch_op.drop_index(batch_op.f("ix_plan_item_user_id"))

    op.drop_table("plan_item")
    with op.batch_alter_table("generation_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_task_user_id"))

    op.drop_table("generation_task")
    with op.batch_alter_table("coverage", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_coverage_material",
            sqlite_where=sa.text("material_id IS NOT NULL"),
            postgresql_where=sa.text("material_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "ux_coverage_assessment",
            sqlite_where=sa.text("assessment_id IS NOT NULL"),
            postgresql_where=sa.text("assessment_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_coverage_user_id"))
        batch_op.drop_index("ix_coverage_user_confirmed")
        batch_op.drop_index("ix_coverage_topic")
        batch_op.drop_index("ix_coverage_material")

    op.drop_table("coverage")
    with op.batch_alter_table("topic_state", schema=None) as batch_op:
        batch_op.drop_index("ix_topic_state_user_due")

    op.drop_table("topic_state")
    with op.batch_alter_table("topic_split", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_split_user_id"))

    op.drop_table("topic_split")
    with op.batch_alter_table("hours_entry", schema=None) as batch_op:
        batch_op.drop_index("ix_hours_entry_user_setup")
        batch_op.drop_index("ix_hours_entry_user_occurred")
        batch_op.drop_index(batch_op.f("ix_hours_entry_user_id"))

    op.drop_table("hours_entry")
    with op.batch_alter_table("exam_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_profile_owner_id"))

    op.drop_table("exam_profile")
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_user_id"))
        batch_op.drop_index("ix_assessment_user_date")

    op.drop_table("assessment")
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_user_id"))

    op.drop_table("topic")
    with op.batch_alter_table("study_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_session_user_id"))

    op.drop_table("study_session")
    with op.batch_alter_table("plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_user_id"))

    op.drop_table("plan")
    with op.batch_alter_table("material", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_material_user_id"))

    op.drop_table("material")
    with op.batch_alter_table("coverage_reading", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coverage_reading_user_id"))

    op.drop_table("coverage_reading")
    with op.batch_alter_table("assessment_slot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_slot_owner_id"))

    op.drop_table("assessment_slot")
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_user_id"))

    op.drop_table("course")
    with op.batch_alter_table("capacity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capacity_user_id"))

    op.drop_table("capacity")
    op.drop_table("user")
    # ### end Alembic commands ###
